### PR TITLE
Implements `DeleteSubscription`

### LINKED ISSUE #56: RemoveSubscription using the new library
Hi,
There is any posibbility to access RemoveSubscription using the new library?

### PR DESCRIPTION
**Pull request by mxa0079**
Fix #56

### CODE REVIEW

**Comment by WestDiscGolf** [comment]
Why is ` string collection = null, ` in the parameters required as it's driven from the `APICollectionType` enum value and determined through the `FormatKey`?

**Comment by mxa0079** [comment]
Good call. I misunderstood `APICollectionType` as a type referencing the API version (which currently is statically set to 1). I will change this and amend.

Probably a good indication to pick a different name for `APICollectionType`. I am thinking `DataCollectionType` thoughts?

**Comment by WestDiscGolf** [comment]
`APICollectionType` as been in since pretty early and believe (not checked) @aarondcoleman added it. Happy to update the name of it however this will break a lot of stuff I'd imagine at your end and others? Better to do it now than later though but will cause issues with migrating?

It however can not be empty (see the add and list method) so it doesn't need to be nullable / optional and the order of parameters is now inconsistent with the other subscription methods which isn't ideal.

An empty string subscriber id isn't valid either (not checked docs though so could be wrong) so needs to be checked for empty and/or whitespace as well as null not just `!= null`.

**Comment by WestDiscGolf** [comment]
Re: Subscriber Id it just says if not present then uses the default. You could read that as either if the header is not present then use the default or if the subscriber id is not present then use the default. However I'd take that as either way comes out at the same conclusion of using the default subscriber id - https://dev.fitbit.com/docs/subscriptions/#request-headers - In this case I think the check should be consistent with the other methods.

As for `ApiCollectionType` this relates to which collections you can have. We already cover the options in ...
```private string FormatKey(APICollectionType apiCollectionType, string format)
        {
            string strValue = apiCollectionType == APICollectionType.user ? string.Empty : apiCollectionType.ToString();
            return string.IsNullOrWhiteSpace(strValue) ? strValue : string.Format(format, strValue);
        }
```
as `user` is everything ie. "All user subscriptions". If we are going to rename the enum though I would also like to update the names of the values to be in line with .net naming guidelines (aka Upper casing the first letter) eg `activities` to `Activities`.

**Comment by mxa0079** [comment]
@WestDiscGolf Collecting can be empty, it just means to delete subscriptions from all collections:

> collection-path	Collection to delete subscription form. **If not present, subscriptions will be deleted from all collections**

The SubscriberId header is recommended but not required, from the docs:

X-Fitbit-Subscriber-Id	**recommended**	The ID of the subscriber to receive notifications, as defined on dev.fitbit.com. If not present, the default subscriber is used.

My interpretation of recommended is that we do not need to pass it, in which case Fitbit will use the default subscriber id for this account.

[Source](https://dev.fitbit.com/docs/subscriptions/#deleting-a-subscription)

As far as `ApiCollectionType` this is a breaking change that will need addressed in V3. See #131

**Comment by WestDiscGolf** [comment]
I think we're on the same page :-)

The X-Fitbit-Subscriber-Id is recommended but optional. This is the same for adding and requesting the list. If there is no value or null then the header isn't added. The remove should be consistent with the Add and List.

The user enums value is a way to indicate all subscriptions. This is a historical decision which has been in the library since almost the beginning hence the FormatKey helper method.

Agreed on the rename of enums to V3 :-)

**Pull request merged**
